/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Tutorial',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.0,
      timeLimitSeconds: null,
      targetScore: 100,
      obstacleCount: 5,
      obstacleSpeed: 1.15,
      collectibleCount: 12,
      collectibleValue: 10,
      backgroundTheme: 'meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Level 2',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.11,
      timeLimitSeconds: null,
      targetScore: 200,
      obstacleCount: 7,
      obstacleSpeed: 1.3,
      collectibleCount: 14,
      collectibleValue: 10,
      backgroundTheme: 'meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Level 3',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.22,
      timeLimitSeconds: 96,
      targetScore: 300,
      obstacleCount: 9,
      obstacleSpeed: 1.45,
      collectibleCount: 16,
      collectibleValue: 10,
      backgroundTheme: 'forest',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Level 4',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.33,
      timeLimitSeconds: 88,
      targetScore: 400,
      obstacleCount: 11,
      obstacleSpeed: 1.6,
      collectibleCount: 18,
      collectibleValue: 10,
      backgroundTheme: 'forest',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Level 5',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.44,
      timeLimitSeconds: 80,
      targetScore: 500,
      obstacleCount: 13,
      obstacleSpeed: 1.75,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'mountain',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Level 6',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.56,
      timeLimitSeconds: 72,
      targetScore: 600,
      obstacleCount: 15,
      obstacleSpeed: 1.9,
      collectibleCount: 22,
      collectibleValue: 10,
      backgroundTheme: 'mountain',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Level 7',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.67,
      timeLimitSeconds: 64,
      targetScore: 700,
      obstacleCount: 17,
      obstacleSpeed: 2.05,
      collectibleCount: 24,
      collectibleValue: 10,
      backgroundTheme: 'cave',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Level 8',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.78,
      timeLimitSeconds: 56,
      targetScore: 800,
      obstacleCount: 19,
      obstacleSpeed: 2.2,
      collectibleCount: 26,
      collectibleValue: 10,
      backgroundTheme: 'cave',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Level 9',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.89,
      timeLimitSeconds: 48,
      targetScore: 900,
      obstacleCount: 21,
      obstacleSpeed: 2.3499999999999996,
      collectibleCount: 28,
      collectibleValue: 10,
      backgroundTheme: 'sky',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Level 10',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: 45,
      targetScore: 1000,
      obstacleCount: 23,
      obstacleSpeed: 2.5,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'sky',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
